services:
  - type: web
    name: familycare-main
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGSCHEMA
        value: familycare
      - key: DATABASE_URL
        sync: false
      - key: SENIOR_BASE_URL
        sync: false
